"""empty message

Revision ID: f499a5c200b6
Revises: 
Create Date: 2023-10-10 13:28:31.807765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f499a5c200b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers_table.id'], name=op.f('fk_tasks_table_engineer_id_engineers_table')),
    sa.ForeignKeyConstraint(['project_id'], ['projects_table.id'], name=op.f('fk_tasks_table_project_id_projects_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_table')
    op.drop_table('projects_table')
    op.drop_table('engineers_table')
    # ### end Alembic commands ###
